image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build

before_script:
  - mkdir -p Xsort/Xsort.WPF
  - echo $APPSETTINGS_JSON > /builds/csharp-projects8840208/Xsort/Xsort.WPF/appsettings.json
  - cat /builds/csharp-projects8840208/Xsort/Xsort.WPF/appsettings.json




build:
  stage: build
  script:
    - dotnet publish -o out -c Release -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRun=true -p:DebugSymbols=false --no-self-contained
  artifacts:
    paths:
      - out/
