image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build

build:
  stage: build
  script:
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet publish -c Release -o out
  artifacts:
    paths:
      - out/
