stages:
  - build
  - release

variables:
  BUILD_DIR: "out"
  PROJECT_PATH: "Xsort.WPF/Xsort.WPF.csproj"
  DOTNET_VERSION: "8.0"
  RUNTIME: "win-x64"
  GIT_USER: "oauth2"
  GIT_PASS: "$GITLAB_PAT"
  GITLAB_API_URL: "https://gitlab.com/api/v4"
  GITLAB_PROJECT_ID: "$CI_PROJECT_ID"

before_script:
  - echo "$APPSETTINGS_JSON" > /builds/csharp-projects8840208/Xsort/Xsort.WPF/appsettings.json
  - LAST_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
  - |
    VERSION_PARTS=(${LAST_TAG//./ })
    MAJOR=${VERSION_PARTS[0]#v}  # Убираем 'v' из версии
    MINOR=${VERSION_PARTS[1]:-0}
    PATCH=${VERSION_PARTS[2]:-0}
    PATCH=$((PATCH + 1))
    NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
    echo "New version: $NEW_VERSION"
    echo "NEW_VERSION=$NEW_VERSION" >> variables.env

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
  - echo "Publishing application..."
  - dotnet publish "$PROJECT_PATH" -o "$BUILD_DIR" -c Release -r "$RUNTIME" -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:IncludeAllContentForSelfExtract=true -p:PublishReadyToRun=true -p:DebugSymbols=false -p:Optimize=true -p:DebugType=None --no-self-contained

  artifacts:
    paths:
      - $BUILD_DIR/
    expire_in: 1 week

release:
  stage: release
  image: mcr.microsoft.com/dotnet/sdk:$DOTNET_VERSION
  script:
    - echo "Creating new tag..."
    - |
    - git config user.email "ci-runner@gitlab.com" &&
      git config user.name "CI Runner" &&
      git tag "$NEW_VERSION" &&
      git remote set-url origin "https://${GIT_USER}:${GIT_PASS}@gitlab.com/csharp-projects8840208/Xsort.git" &&
      git push origin "$NEW_VERSION"
    - echo "Creating release..."
    - export RELEASE_TAG="v$NEW_VERSION"
    - export RELEASE_NAME="Release $NEW_VERSION"
    - export RELEASE_DESCRIPTION="Release created for version $NEW_VERSION from commit $CI_COMMIT_SHA"
    - >
      curl --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
      --data-urlencode "tag_name=$RELEASE_TAG" \
      --data-urlencode "name=$RELEASE_NAME" \
      --data-urlencode "description=$RELEASE_DESCRIPTION" \
      --data-urlencode "ref=$CI_COMMIT_SHA" \
      --form "assets[files][]=@$CI_PROJECT_DIR/$BUILD_DIR/Xsort.exe" \
      "$GITLAB_API_URL/projects/$GITLAB_PROJECT_ID/releases"
  dependencies:
    - build
  only:
    - main
