image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build

before_script:
  - mkdir -p Xsort/Xsort.WPF
  - echo "$APPSETTINGS_JSON" > Xsort/Xsort.WPF/appsettings.json
  - cat Xsort/Xsort.WPF/appsettings.json  # Проверка содержимого




build:
  stage: build
  script:
    - ls -la Xsort/Xsort.WPF
    - dotnet restore
    - dotnet build --configuration Release
    - dotnet publish -c Release -o out
  artifacts:
    paths:
      - out/
